# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


stages:
- stage: stgA
  jobs:
  - job: jbA1
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - checkout: none
    - script: echo A1!
  - job: jbA2
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - checkout: none
    - script: echo A2!

- stage: stgB
  dependsOn: stgA
  jobs:
  - job: jbB1
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - checkout: none
    - script: echo B1!


    

