# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


stages:
- stage: stg-A
  jobs:
  - job: jb-A1
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - checkout: none
    - script: echo A1!
  - job: jb-A2
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - checkout: none
    - script: echo A1!

- stage: stg-B
  dependsOn: stg-A
  jobs:
  - job: jb-b1
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - checkout: none
    - script: echo B!


    

